config/routes.rb
Bretflix::Application.routes.draw do
  resources :movies

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  get "home/index"

  root :to => 'home#index'

   match ':controller(/:action(/:id(.:format)))'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  #paginate_per 10
  
  validates_presence_of :title
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me

  validates_presence_of :name, :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery

  private

  def after_sign_out_path_for(resource_or_scope)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    send(:"new_#{scope}_session_path")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
  puts params.inspect
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end

  def checkout
    @movie = Movie.find(params[:id])  
    @movie.update_attributes!(:user => current_user)

    redirect_to :action => :index
  end

  def return
    @movie = Movie.find(params[:id])  
    @movie.update_attributes!(:user => nil) if @movie.user == current_user

    redirect_to :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/home/index.html.haml
#block-text.block
  .content
    %h2.title Home
    .inner
      %p.first
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
      %p
        %span.small Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %p
        %span.gray Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %hr/
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
- content_for :sidebar, render(:partial => 'sidebar')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bretflix
    = stylesheet_link_tag 'web-app-theme', 'web-app-theme/base', 'web-app-theme/themes/default/style', 'application'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Bretflix
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              =link_to t("web-app-theme.logout", :default => "Logout"), logout_path
        #main-navigation
          %ul.wat-cf
            %li{ :class => (params[:controller] == "home" ? "first active" : "first") }
              = link_to "Home", root_path
            %li{ :class => (params[:controller] == "blog_entries" ? "active" : nil) }
              = link_to "Movies", movies_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} Bretflix.
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title MBretflix
    = stylesheet_link_tag "web_app_theme"
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/movies/_form.html.haml
.group
  = f.label :title, t("activerecord.attributes.movie.title", :default => "Title"), :class => :label
  = f.text_field :title, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :genre, t("activerecord.attributes.movie.genre", :default => "Genre"), :class => :label
  = f.text_field :genre, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :user_id, t("activerecord.attributes.movie.user_id", :default => "User"), :class => :label
  = f.number_field :user_id, :class => 'number_field'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), movies_path, :class => "text_button_padding link_button"

app/views/movies/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/movies/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", movies_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_movie_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_movie_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Movie
    .inner
      = form_for @movie, :url => movie_path(@movie), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/movies/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", movies_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_movie_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Movies
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.movie.title", :default => t("activerecord.labels.title", :default => "Title"))
          %th
            = t("activerecord.attributes.movie.genre", :default => t("activerecord.labels.genre", :default => "Genre"))
          %th Checked Out By
        - @movies.each do |movie|
          %tr{:class => cycle("odd", "even")}
            %td
              = movie.id
            %td
              = link_to movie.title, movie_path(movie)
            %td
              = movie.genre
            %td
              -if movie.user 
                -if movie.user == current_user
                  = button_to 'return', :action => 'return', :id => movie.id
                -else
                  = movie.user.try(:name)
              -else
                = button_to 'checkout', :action => 'checkout', :id => movie.id 
      .actions-bar.wat-cf
        .actions
        = paginate @movies
- content_for :sidebar, render(:partial => 'sidebar')

app/views/movies/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", movies_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_movie_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Movie
    .inner
      = form_for :movie, :url => movies_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/movies/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", movies_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_movie_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", movie_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.movie.title", :default => t("activerecord.labels.title", :default => "Title"))
          \:
        = @movie.title
      %p
        %b
          = t("activerecord.attributes.movie.genre", :default => t("activerecord.labels.genre", :default => "Genre"))
          \:
        = @movie.genre
      %p
        %b
          = t("activerecord.attributes.movie.user_id", :default => t("activerecord.labels.user_id", :default => "User"))
          \:

      -if @movie.user 
        -if @movie.user == current_user
          = button_to 'return', :action => 'return', :id => @movie.id
        -else
          = @movie.user.try(:name)
      -else
        = button_to 'checkout', :action => 'checkout', :id => @movie.id 
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_movie_path(@movie), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), movie_path(@movie), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')